"""Exact frame relations and element-preserving seat transfer (M07).

relation(a,b) = frame(a)^-1 AFTER frame(b), mapping B positions to A.
Delivery from A to B uses its INVERSE. Human relation names are not elected.
"""
from .gf2 import Affine, unit
from .model_a import TYPES, POSITION, BY_POSITION, frame, position


def relation(a: str, b: str) -> Affine:
    return frame(a).inverse().compose(frame(b))


def apply_relation(tim: str, transform: Affine) -> str:
    target = frame(tim).compose(transform)
    for t in TYPES:
        if frame(t) == target:
            return t
    raise ValueError("transformation is not a lawful relation action")


def all_relations() -> frozenset[Affine]:
    return frozenset(relation(TYPES[0], t) for t in TYPES)


def landing_position(sender: str, p: int, receiver: str) -> int:
    return BY_POSITION[relation(sender, receiver).inverse()(position(p))]


def landing_permutation(sender: str, receiver: str) -> tuple[int, ...]:
    return tuple(landing_position(sender, p, receiver) for p in POSITION)


# M08: a static source-defined permutation, never an automatic tick policy.
ESTAFETTE = Affine(((0,0,1), (0,1,0), (1,0,0)), (0,0,1))


def extended_group() -> frozenset[Affine]:
    """Finite group generated by relations and estafette, UMA §10."""
    generators = tuple(all_relations()) + (ESTAFETTE,)
    found, pending = {unit()}, [unit()]
    while pending:
        current = pending.pop()
        for generator in generators:
            candidate = generator.compose(current)
            if candidate not in found:
                found.add(candidate)
                pending.append(candidate)
    return frozenset(found)
