"""Self-contained evidence inspector; no server or remote resources."""
import argparse,json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]

HTML='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>HLE · C4 composition and nested meaning</title>
<style>
:root{color-scheme:dark;--bg:#10151d;--card:#1a2230;--line:#344052;--muted:#b0bed0;--ink:#eff4fa;--accent:#80dfc1;--gold:#ffcb7b}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.55 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:40px 28px}h1{font-size:38px;line-height:1.15;margin:12px 0}h2{font-size:23px;margin:0 0 14px}h3{font-size:17px;margin:0 0 8px}p{margin:8px 0 18px}.eyebrow{letter-spacing:.12em;font-size:12px;color:var(--accent);text-transform:uppercase}.intro{max-width:850px;color:var(--muted)}.stats,.answers{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:24px 0}.stat,.box{border:1px solid var(--line);background:var(--card);border-radius:12px;padding:18px}.stat strong{display:block;font-size:29px;color:var(--accent)}.stat span,.muted{color:var(--muted)}.controls{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin:30px 0 20px}select,button{background:#202c3e;color:var(--ink);border:1px solid #60718a;border-radius:6px;padding:11px 13px;font:inherit}select{max-width:100%}button{cursor:pointer}button.active{background:var(--accent);color:#10291f}.pill{display:inline-block;border-radius:4px;padding:3px 8px;background:#294235;color:#a9f0d2;font-size:13px}.pill.warning{background:#4b3725;color:var(--gold)}table{width:100%;border-collapse:collapse;margin:18px 0}th,td{padding:11px 12px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-size:13px;font-weight:600}.table-wrap{overflow:auto}.metrics{display:flex;gap:40px;flex-wrap:wrap;margin:20px 0}.metrics strong{font-size:26px;display:block}details{border:1px solid var(--line);border-radius:8px;padding:12px;margin:12px 0}summary{cursor:pointer}pre{white-space:pre-wrap;word-break:break-word;font:12px/1.5 ui-monospace,monospace;max-height:440px;overflow:auto}section{margin:38px 0}.notice{border-left:3px solid var(--gold);padding-left:15px;color:var(--muted)}.flow{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.flow span{padding:8px 12px;border:1px solid var(--line);border-radius:6px}.flow small{display:block;color:var(--muted)}a{color:var(--accent)}@media(max-width:760px){main{padding:25px 16px}h1{font-size:30px}.stats,.answers{grid-template-columns:1fr}.controls{align-items:stretch;flex-direction:column}}
</style><main><div class="eyebrow">HLE / Full Crux / Milestone C4</div><h1>Composition and nested meaning</h1>
<p class="intro">Follow generated content across perspectives, then inspect the child evidence that justifies a parent result. Equal endpoints preserve neither the meaning nor the consequences of a journey.</p>
<div class="stats"><div class="stat"><strong>4 / 7</strong><span>Milestones complete within their declared gates</span></div><div class="stat"><strong id="tests">—</strong><span>Passing methods in the final regression run</span></div><div class="stat"><strong>7 pairs</strong><span>Changed downstream use at matched focus spending</span></div></div>
<div class="controls"><label for="case">Evidence case</label><select id="case"></select><button id="good" class="active">Healthy</button><button id="bad">Semantic control</button></div>
<section id="detail"></section><section><h2>Child failure remains visible</h2><p id="blocked"></p><p class="notice">A successful review is separate from a completed parent outcome. A cancelled child blocks release; its performed work remains charged. Shared descendants are counted once in the cited-operation union. The parent pays only its own review.</p></section>
<section><h2>Measured costs</h2><p class="muted">The same five circuits include content retention, exchanges, paid receipt reads, parent review and later consumers. Engine setup is excluded from active timing; restore and audit are separate.</p><div id="measure"></div></section>
<section><h2>Declared scope</h2><p>One consumable-workshop language; two-member exchanges; one actor's child operations per parent; up to eight direct children, four nested levels and 64 distinct cited operations. Context transfer requires local evidence and does not copy authority. Summaries and lessons confer no practiced competence.</p><p class="notice">All full-release cells remain open for applicable remaining gates. Next: C5 — Shell formation and development across the map. C6 addresses situated selection and transfer; C7 addresses the sustained full-Crux release.</p></section>
<footer class="muted">Evidence is supplied as raw transactions, access archives and exact checkpoints in the accompanying C4 evidence package. This page displays recorded results; it does not run the engine.</footer></main>
<script id="evidence" type="application/json">__DATA__</script><script>
const data=JSON.parse(document.getElementById('evidence').textContent);let control=false;const cases=[...new Set(data.witnesses.rows.map(r=>r.name))];const el=id=>document.getElementById(id);
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function unpack(x){if(x===null||typeof x!=='object')return x;if(x.tuple)return x.tuple.map(unpack);if(x.record==='ObjectRef')return unpack(x.fields.identity)+' @'+x.fields.revision;if(x.record==='ObjectId')return x.fields.namespace+':'+x.fields.key;if(x.enum)return x.value;return Object.fromEntries(Object.entries(x).map(([k,v])=>[k,unpack(v)]));}
function dict(x){let y=unpack(x);return Array.isArray(y)?Object.fromEntries(y):y;}
el('case').innerHTML=cases.map(n=>'<option>'+esc(n)+'</option>').join('');el('tests').textContent=data.tests?.passed?data.tests.tests:'Pending';
function render(){const row=data.witnesses.rows.find(r=>r.name===el('case').value&&r.control===control),good=data.witnesses.rows.find(r=>r.name===row.name&&!r.control),bad=data.witnesses.rows.find(r=>r.name===row.name&&r.control);
el('good').classList.toggle('active',!control);el('bad').classList.toggle('active',control);
let children=row.children.map(c=>'<tr><td>'+esc(c.route)+'</td><td>'+esc(c.polarity)+'</td><td>'+esc(c.status)+'</td><td>'+c.spent+'</td></tr>').join('');
el('detail').innerHTML='<h2>'+esc(row.name)+'</h2><span class="pill '+(control?'warning':'')+'">'+(control?'Intervention rejected by semantic audit':'Independent audit passed')+'</span><div class="answers"><div class="box"><h3>What changed?</h3>'+esc(good.what_changed)+'</div><div class="box"><h3>How did it change?</h3>'+esc(good.how)+'</div><div class="box"><h3>What becomes possible?</h3>'+esc(good.later_use)+'</div></div><div class="metrics"><div><strong>'+good.outcome+' / '+bad.outcome+'</strong><span class="muted">Later amount · healthy / control</span></div><div><strong>'+row.focus_spent+'</strong><span class="muted">Matched focus work units</span></div><div><strong>'+row.active_modeled_work+'</strong><span class="muted">Total active work in this branch</span></div></div>'+
(children?'<h3>Declared child movements</h3><div class="table-wrap"><table><thead><tr><th>Route</th><th>Polarity</th><th>Operation status</th><th>Paid units</th></tr></thead><tbody>'+children+'</tbody></table></div>':'')+
(row.parent?'<p>Parent outcome: <b>'+ (row.parent_complete?'complete':'blocked')+'</b>. Cited child work: '+dict(row.parent).cited_spending+' units. Physical stock consumed: '+row.supply_consumed+' units.</p>':'')+
(control?'<p class="notice">'+esc(row.control_rejection)+'</p>':'')+
row.children.map((c,i)=>'<details><summary>Child '+(i+1)+' · '+esc(c.route)+' content and exact references</summary><pre>'+esc(JSON.stringify({operation:unpack(c.operation),output:unpack(c.output),content:dict(c.content)},null,2))+'</pre></details>').join('')+
'<details><summary>Exact evidence references and parent record</summary><pre>'+esc(JSON.stringify({references:Object.fromEntries(Object.entries(row.refs).map(([k,v])=>[k,unpack(v)])),parent:row.parent?dict(row.parent):null,checkpoint_sha256:row.checkpoint_sha256},null,2))+'</pre></details>';}
el('case').onchange=render;el('good').onclick=()=>{control=false;render()};el('bad').onclick=()=>{control=true;render()};
el('blocked').textContent='The retained cancelled-child witness passes audit. Parent outcome: blocked; later permitted amount: '+data.witnesses.blocked.outcome+'.';
if(data.measurements){const m=data.measurements;el('measure').innerHTML='<p>'+m.workers+' isolated workers · unchanged C3 median ratio '+m.c3_ratio.toFixed(3)+' (limit 1.5) · fixed-history active ratio '+m.history_ratio.toFixed(3)+' (limit 1.75).</p><div class="table-wrap"><table><thead><tr><th>History</th><th>Records/case</th><th>Active ms</th><th>Restore s</th><th>Audit s</th><th>Raw MiB</th></tr></thead><tbody>'+m.rows.filter(r=>r.lane==='panel').map(r=>'<tr><td>'+r.shape+'</td><td>'+r.inactive+'</td><td>'+(1000*r.median_active_wall_seconds).toFixed(1)+'</td><td>'+r.median_restore_seconds.toFixed(2)+'</td><td>'+r.median_audit_seconds.toFixed(2)+'</td><td>'+(r.checkpoint_bytes/1048576).toFixed(2)+'</td></tr>').join('')+'</tbody></table></div>';}else el('measure').textContent='Measurements pending.';
render();</script></html>'''


def main():
    p=argparse.ArgumentParser();p.add_argument('--evidence',type=Path,default=ROOT/'evidence_c4');p.add_argument('--out',type=Path,required=True);a=p.parse_args()
    def read(path):return json.loads(path.read_text()) if path.exists() else None
    data=dict(witnesses=read(a.evidence/'witnesses/summary.json'),tests=read(a.evidence/'tests_final/summary.json'),measurements=read(a.evidence/'measurements/summary.json'))
    # Full per-test timings remain in evidence; the UI needs only the result.
    if data['tests']:data['tests']={k:v for k,v in data['tests'].items() if k!='rows'}
    a.out.write_text(HTML.replace('__DATA__',json.dumps(data,ensure_ascii=True).replace('<','\\u003c')))

if __name__=='__main__':main()
